# Generated by Django 5.1.7 on 2025-03-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainers/')),
            ],
        ),
    ]
