# Generated by Django 5.1.7 on 2025-03-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_hire'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiredTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=255)),
                ('trainer_specialty', models.CharField(max_length=255)),
                ('trainer_experience', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('hired_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hire',
        ),
    ]
