# Generated by Django 5.1.7 on 2025-03-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('trainer', models.CharField(max_length=100)),
            ],
        ),
    ]
